service: valkyrie-images

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.6

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /image
          method: get

custom:
  pythonRequirements:
    zip: true

package:
  include:
    - '*.py'
    - 'opencv-python'
    - 'numpy'
    - 'exif'
    - 'Pillow'

plugins:
  - serverless-python-requirements
